# Generated by Django 4.2.3 on 2024-02-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="app/product_images/"),
        ),
    ]
