# Generated by Django 4.2.3 on 2024-02-29 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=250)),
                ("email_address", models.EmailField(max_length=150, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\d{10}", "Phone number must be 10 digits"
                            )
                        ],
                    ),
                ),
                ("additional_notes", models.TextField(max_length=500)),
                ("accepted_terms", models.BooleanField(default=False)),
                ("service_required", models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
