# Generated by Django 4.2.3 on 2024-02-29 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_service_remove_product_category_delete_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="enquiries",
            name="created_at",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
