# Generated by Django 4.2.3 on 2024-02-29 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_client_created_at_enquiries_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="additional_notes",
            new_name="message",
        ),
    ]
