# Generated by Django 4.2.3 on 2024-02-29 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_rename_additional_notes_service_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
