# Generated by Django 4.2.3 on 2024-02-29 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_delete_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=250)),
                ("email_address", models.EmailField(max_length=150)),
                ("phone_number", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("accepted_terms", models.BooleanField(default=False)),
                ("service_required", models.CharField(max_length=300)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
